#!/usr/bin/env python3
import requests
import subprocess
from datetime import datetime
import time

def get_img(limit=1):
    try:
        request = requests.get(f'https://api.thecatapi.com/v1/images/search?limit={limit}')
    except:
        return "erro ao acessar a internet"
    
    if request.status_code == 200:
        urls = [i['url'] for i in request.json()[:limit]]
        return request.json()[0]['url'] if limit==1 else urls
    
    return "erro ao coletar imagem"


def generete_unique_arq_name():
    date = datetime.now()
    return f"{date.year}{date.month}{date.day}{date.hour}{date.minute}{date.second}-CATimg.jpg"

def baixar_img(url_img):
    arq_name = generete_unique_arq_name()
    cmd = subprocess.run(f"wget -O {arq_name} {url_img}",shell=True, capture_output=True)
    return arq_name

def display(arq_name):
    subprocess.run(f'catimg -w 100 {arq_name}',shell=True)
    return arq_name

def del_img(arq_name):
    subprocess.run(f'rm -f {arq_name}',shell=True)


del_img(display(baixar_img(get_img())))

print(__name__)
